version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: trading-card-server
    container_name: trading-card-node-server
    command: npm start
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: trading-card-client
    container_name: trading-card-react-client
    command: npm start
    volumes:
      - ./client:/app
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
